feat: feedback form blueprint
arcjet/arcjet-docs pull request #227
Opened 2024-11-07 20:18 UTC by danni-popova

2024-11-07 22:34 UTC, blaine-arcjet commented on src/content/docs/blueprints/feedback-form.mdx
> +Feedback forms are often used as tools for gathering valuable insights to improve services, products, or experiences.Spam undermines this integrity and could distract from the original goals of the s
```suggestion
Feedback forms are often used as tools for gathering valuable insights to improve services, products, or experiences. Spam undermines this integrity and could distract from the original goals of the survey or feedback initiative.
```

2024-11-07 22:34 UTC, blaine-arcjet commented on src/content/docs/blueprints/feedback-form.mdx
> +Protecting forms ensures that only genuine, thoughtful feedback is collected and used appropriately.Arcjet can help you protect your feedback forms from spam and invalid contact details.
```suggestion
Protecting forms ensures that only genuine, thoughtful feedback is collected and used appropriately. Arcjet can help you protect your feedback forms from spam and invalid contact details.
```

2024-11-07 22:34 UTC, blaine-arcjet commented on src/content/docs/blueprints/feedback-form.mdx
> +- Bot Detection– Automatically identify and block bot traffic, keeping automated spammers and malicious scripts from submitting your forms.
```suggestion
- Bot Detection – Automatically identify and block bot traffic, keeping automated spammers and malicious scripts from submitting your forms.
```

2024-11-08 16:18 UTC, davidmytton requested changes
Can you include the feedback form component and handler like I did on the payment form example?

2024-12-07 07:33 UTC, davidmytton requested changes
The API handler that the form `POST`s to is missing.

2025-02-08 07:49 UTC, davidmytton approved these changes

2025-02-08 07:49 UTC, merged